apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: karsajobs-frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: karsajobs-frontend
        image: wildanbudiawanz/karsajobs-ui:latest
        ports:
        - containerPort: 8000
        env:
          - name: VUE_APP_BACKEND
            value: http://10.122.0.44:30000