# versi dockercompose 3.7
version: "3.7"

# mendefinisikan service-service yang akan di up
services:
  # service pertama
  item-app:
    # agar bisa run di apple m1
    platform: linux/amd64

    # image yang dibuild dari dockerfile
    image: item-app:v1

    # restart policy selalu restart ketika berhenti
    restart: always

    # mapping port sehingga bisa diakses pada 80
    ports:
      - 80:8080

    # memastikan service item-db berjalan terlebih dahulu
    depends_on:
      - item-db

  # service yang kedua
  item-db:
    # image mongo tags 3
    image: mongo:3

    #  restart policy selalu restart ketika berhenti
    restart: always

    # Memakai volume bernama app-db dengan target /data/db di container
    volumes:
      - app-db:/data/db

# mendefinisikan volume app-db yang digunakan
volumes:
  app-db:
